### PR TITLE
fix for NXbeam...

### PR DESCRIPTION
**Pull request by sanbrock**

### CODE REVIEW

**Review by lukaspie — APPROVED** [review]
LGTM.

Any particular reason why the order of input,output attributes and dimensions was changed? Should not make a difference for the nyaml tool

**Comment by sanbrock** [comment]
While the order is irrelevant for nyaml tool, the nxdl specification requires the dimensions to be declared before any attributes.

**Comment by lukaspie** [comment]
I cannot find that specification in the nxdl.xsd. Is it just how the things are ordered [here](https://github.com/FAIRmat-NFDI/nexus_definitions/blob/a048e9f2a207d61c1be5429bad23648d5cf88b39/nxdl.xsd#L637)? If the order of these things ist important, shouldn't our tool sort them automatically?

**Comment by sanbrock** [comment]
The elements are in a sequence which means in an ordered list. In fact, the nyaml could take care of it which could be a new nice convenience feature.

**Comment by lukaspie** [comment]
Ok, I'll add an issue in the nyaml repo. I don't think all of our definitions currently respect this ordering.

**Review by RonHildebrandt — COMMENTED** [review]
Everything is fine

**Pull request merged**
