### PR TITLE
Convenience functions for nyaml ⇄ nxdl and gh pages build

### PR DESCRIPTION
**Pull request by domna**
This adds:

- Cached building form yaml to nxdl
- Build to gh pages for fairmat and the branch name in subdirectory (fairmat builds to https://fairmat-nfdi.github.io/nexus_definitions/index.html#, any other branch to .../branchname, e.g., https://fairmat-nfdi.github.io/nexus_definitions/specific-nyaml-nxdl-compilation/ for this branch)

### CODE REVIEW

**Comment by lukaspie** [comment]
Thanks for this PR, this looks very helpful. I have tested it and you can find some comments below.

> * [x]  Adds yaml files to `.gitignore`

I don't agree that this is a good idea. There could be problems locally if I make changes to my nyaml files which I would like to commit first (to keep track of what I am doing) which would not be possible now. Especially since one `make clean-nyaml` would delete all of my changes. One workaround could be to have a different gitignore locally. But I also don't have a problem with having the proposed changed nyamls in a PR also on Github since there it may be easier to understand a new idea. We could then just delete them right before merging. Does this not work with the proposed changes in the Makefile?

> * [x]  Use make correctly to compile changed files only

This worked seamlessly for me. Keeping track of the changed files is very cool. Is there any specific reason why it needs to make all nyaml files? If not, it would be nice if it could also only create the nyamls for changed nxdls, e.g. after pulling new changes from remote.

One more thing that would potentially  be useful would be if one could only make the nxdl/nyamls that are mentioned in another class. For example, if I run `make contributed_definitions/NXmpes_parsed.yaml` (maybe with a flag), it would create all nyamls that are part of NXmpes (like `NXsample.yaml`, `NXinstrument.yaml`, and so on). Is that helpful/possible?

**Comment by domna** [comment]
> Thanks for this PR, this looks very helpful. I have tested it and you can find some comments below.
> 

Thanks for testing this!
> > * [x]   Adds yaml files to `.gitignore`
> 
> I don't agree that this is a good idea. There could be problems locally if I make changes to my nyaml files which I would like to commit first (to keep track of what I am doing) which would not be possible now. Especially since one `make clean-nyaml` would delete all of my changes. One workaround could be to have a different gitignore locally. But I also don't have a problem with having the proposed changed nyamls in a PR also on Github since there it may be easier to understand a new idea. We could then just delete them right before merging. Does this not work with the proposed changes in the Makefile?

I don't fully understand your point. This proposal is to leave yaml files out of the repository entirely. I added the cached version in the direction yaml -> nxdl, because you can run the command after each change, keeping the nxdl up to date and the source of truth. This should then be commited and you can always regenerate your yaml file from this. The yaml files should never be commited. I know currently we keep them with our files in some branches and I think we should discuss in our team meeting whether this is something we want to do or not. We could also reintroduce yaml files into the `fairmat` branch, which I would strongly like. Because IMO the diff on yaml files is a lot easier to read and discuss compared to the xml file diff. However, if we just add them in the branch when we work on we never see a diff w.r.t what has changes to the old version, which renders working with yaml files a bit useless.
> 
> > * [x]   Use make correctly to compile changed files only
> 
> This worked seamlessly for me. Keeping track of the changed files is very cool. Is there any specific reason why it needs to make all nyaml files? If not, it would be nice if it could also only create the nyamls for changed nxdls, e.g. after pulling new changes from remote.

Yes, I tried to *make* it work (☺️). However, since we compile from nxdl to yaml and vice versa `make` ends up in a cyclic dependency if I don't use the trick I used (I essentially tell `make` another target, that's why you have to tell it make to build `_parsed.yaml` files, but actually they will be moved to the `nyaml` directory). I could introduce an additional cache directory or keep the `_parsed.yaml` files and just copy them at the appropriate dir. That way make would still see the files and would be able to keep track of this. But I'm not sure if this wouldn't clutter the repo too much.
> 
> One more thing that would potentially be useful would be if one could only make the nxdl/nyamls that are mentioned in another class. For example, if I run `make contributed_definitions/NXmpes_parsed.yaml` (maybe with a flag), it would create all nyamls that are part of NXmpes (like `NXsample.yaml`, `NXinstrument.yaml`, and so on). Is that helpful/possible?

This is not directly possible, because `make` does not know anything about the dependencies. We could, however, add a feature to `nyaml2nxdl` to list the base classes it uses. That way we could pick it up with make and build them as well. But this is again hacking around what make is actually designed for and I'm not sure if it's worth to spend the time on this, because one can just quickly generate the base class yaml's whenever one needs to change something there.

**Comment by domna** [comment]
Ah... I've just seen that this is still not working as intended, because make is picking also making the nxdls from yaml first, before generating the nxdl.... so we might need to use the old for-loop based method, which does not even allow for making a single targeted file.

**Comment by lukaspie** [comment]
> I know currently we keep them with our files in some branches and I think we should discuss in our team meeting whether this is something we want to do or not. We could also reintroduce yaml files into the `fairmat` branch, which I would strongly like. Because IMO the diff on yaml files is a lot easier to read and discuss compared to the xml file diff. However, if we just add them in the branch when we work on we never see a diff w.r.t what has changes to the old version, which renders working with yaml files a bit useless.

Yeah, the more I think about it, the more this is what I am arguing for 😆  what I was talking about is that locally, if I have a number of changes, I can commit them with the yaml files and then I have a diff between these committed yamls and any new changes I do afterwards.

I agree that your initial solution and also this idea of creating the nyamls for _just_ one appdef seem a bit hacky, so maybe let's just keep the for-loop then. Maybe it is better to change things on nyaml2nxdl and not in the Makefile.

**Comment by domna** [comment]
> > I know currently we keep them with our files in some branches and I think we should discuss in our team meeting whether this is something we want to do or not. We could also reintroduce yaml files into the `fairmat` branch, which I would strongly like. Because IMO the diff on yaml files is a lot easier to read and discuss compared to the xml file diff. However, if we just add them in the branch when we work on we never see a diff w.r.t what has changes to the old version, which renders working with yaml files a bit useless.
> 
> Yeah, the more I think about it, this is what I am arguing for 😆 what I was talking about is that locally, if I have a number of changes, I can commit them (incl. the yaml files) and then I have a diff between these committed yamls and any new changes I do afterwards. It is all also possible with in-between conversion, but it is often so much easier to directly use the nyamls.
> 
> I agree that your initial solution and also this idea of creating the nyamls for _just_ one appdef seem a bit hacky, so maybe let's just keep the for-loop then. Maybe it is better to change things on nyaml2nxdl and not in the Makefile.

I think I could make it work in both ways with using a temporary directory for nxdl *and* yaml. But lets discuss tomorrow in DSUM what we want in `.gitignore` and what workflow we want and then I'll adapt the makefile appropriately.

**Review by sanbrock — APPROVED** [review]
LGTM

**Pull request merged**
