### PR TITLE
Fix that attributes are found as fields

### PR DESCRIPTION
**Pull request by domna**
Fix that attributes are found as fields if they have there are fields with the same name.

### CODE REVIEW

**Comment by sanbrock** [comment]
Line 327 is still makes a preferred assignment to fields rather than to attributes. The code here should also check for type of the concept.

**Comment by domna** [comment]
> Line 327 is still makes a preferred assignment to fields rather than to attributes. The code here should also check for type of the concept.

I think it's fine because line 351 already avoids calling `get_own_nxdl_child_base_types` if `nexus_type` does not match.

**Comment by sanbrock** [comment]
Indeed, but only if it was provided by the caller

**Review by sanbrock — APPROVED** [review]
LGTM

**Review by mkuehbach — APPROVED** [review]
Makes sense plus less iterations for many cases

**Pull request merged**
