### PR TITLE
Fixes NXellipsometry

### PR DESCRIPTION
**Pull request by domna**

### CODE REVIEW

**Review by sanbrock — APPROVED** [review]
LGTM

**Comment by tomio13** [comment]
I know, I am kind of outsider now, but do I see correctly that between this submission in June and the previous from Carola, a large part of the definition was deleted or migrated somewhere else? It would be nice to have it indicated in the comments, or explained...

**Comment by domna** [comment]
mmh... I don't see any changes in the history. Before my changes here, which just fixed some typos Carola was the last person doing changes on the definitions. See https://github.com/FAIRmat-NFDI/nexus_definitions/commits/fairmat/contributed_definitions/NXellipsometry.nxdl.xml

I think a lot of fields were moved into NXopt by Carola as NXellipsometry now inherits from NXopt. Could this be the reason that you are not finding most of the fields?

**Comment by tomio13** [comment]
Yep, you are right.
What I am missing is that all the calibration part seems to be gone, but it was Carola moving it out on 30th of May 2023. It just makes me wonder ... could we just use a link to another experiment? I should dig into my logs to check it out.

**Pull request merged**
