### PR TITLE
Adds function for vcs based versioning (similar to setuptools-scm)

### LINKED ISSUE #80: Implement a get version function
It was decided that NIAC will not support packaging with nexus_definitions. Therefore, we want to have a possibility to extract the nexus version with a function. The idea is to follow setuptools_scm's scheme based on git tags and commits (maybe it's possible to use their internal function for retrieving this information) as version tag (i.e., v2023.10+dev10g<hash> for a commit which has a 10 commit distance from the 2023.10 version and also supports adding dirty tags to show that there where local changes).

### PR DESCRIPTION
**Pull request by domna**
Fixes #80

### CODE REVIEW

**Comment by sherjeelshabih** [comment]
Does this require git to be installed? And does this work when we simply do a pip install from pypi instead of git clone then pip install?

**Comment by domna** [comment]
Indeed, this does require to have git installed. We could also use something like https://github.com/gitpython-developers/GitPython. But even setuptools_scm uses the native git command.

Installing from packaging is not tested yet. However, the nexus definitions themself will not be provided as a package as @sanbrock reported from the last NIAC meeting (see https://github.com/nexusformat/definitions/pull/1303#issuecomment-1773021205). I don't know what happens when pynxtools is installed with nexus_definitions as a submodule. But we should ensure this works before we merge this and https://github.com/FAIRmat-NFDI/pynxtools/pull/124.

**Comment by sherjeelshabih** [comment]
> ~I don't know what happens when pynxtools is installed with nexus_definitions as a submodule. But we should ensure this works before we merge this and [FAIRmat-NFDI/pynxtools#124](https://github.com/FAIRmat-NFDI/pynxtools/pull/124).~ <- This doesn't work. It gives an empty version string because definitions are not a git repo as soon as python copies them to site-packages. So we probably need to hook into the setup process and set the version somehow...

Should we discuss this in the TF meeting tomorrow? I think this is important to think this through. We can discuss both scenarios. One with NIAC accepting this kind of versioning. And the other where we embed this only in pynxtools.

**Comment by domna** [comment]
This could be a solution: https://setuptools.pypa.io/en/latest/userguide/extension.html#defining-additional-metadata
When building add an additional metadata file containing the version used. The function then would check whether this file is available and gets the version from there in any other case it deduces it from vcs.

**Comment by domna** [comment]
Closing this, general support is open for discussion in https://github.com/nexusformat/definitions/pull/1318 and we support this in pynxtools via https://github.com/FAIRmat-NFDI/pynxtools/pull/124 w/o this change.

**Pull request closed without merging**
