### PR TITLE
Change `get_enums` to return a list

### PR DESCRIPTION
**Pull request by domna**
@rettigl

### CODE REVIEW

**Comment by rettigl** [comment]
@domna This seems to work with

```
def is_value_valid_element_of_enum(value, elem) -> Tuple[bool, list]:
    """Checks whether a value has to be specific from the NXDL enumeration and returns options."""
    if elem is not None:
        enums = nexus.get_enums(elem)
        if enums and (
            isinstance(value, list) or value not in enums or value == ""
        ):
            return False, enums
    return True, []
```

**Comment by rettigl** [comment]
But I don't overlook where else this is used. I suggest to also make this a warning instead of Exceptions:
https://github.com/FAIRmat-NFDI/pynxtools/blob/6960709e974a39a55d139f5c6430aaa1bdcc38e1/pynxtools/dataconverter/helpers.py#L632

**Comment by domna** [comment]
Thanks for the comments. I agree with your suggestions and will add it in https://github.com/FAIRmat-NFDI/pynxtools/pull/313

**Review by sanbrock — COMMENTED** [review]
LGTM

**Review by sanbrock — APPROVED** [review]

**Pull request merged**
